Repository meilisearch/meilisearch-dotnet, pull requests merged in 2020-10, with the labels that each got.

#66 Add missing features
  src/Meilisearch/HealthObject.cs
  src/Meilisearch/Index.cs
  src/Meilisearch/IndexStats.cs
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/Stats.cs
  tests/Meilisearch.Tests/IndexTests.cs
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
Labels: Hacktoberfest

#62 Changes about the MeiliSearch's next release (v0.15.0)
  README.md
  tests/Meilisearch.Tests/SearchTests.cs
Labels: skip-changelog

#70 Update version for the next release (v0.3.2)
  src/Meilisearch/Meilisearch.csproj
Labels: skip-changelog

#68 Improve tests
  tests/Meilisearch.Tests/DocumentFixture.cs
  tests/Meilisearch.Tests/DocumentTests.cs
  tests/Meilisearch.Tests/IndexFixture.cs
  tests/Meilisearch.Tests/IndexTests.cs
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
  tests/Meilisearch.Tests/Movie.cs
  tests/Meilisearch.Tests/SearchTests.cs
  tests/Meilisearch.Tests/SettingsTests.cs
  tests/Meilisearch.Tests/UpdateStatusTests.cs
Labels: skip-changelog

#72 Rename global settings methods
  src/Meilisearch/Index.cs
  tests/Meilisearch.Tests/IndexFixture.cs
  tests/Meilisearch.Tests/SettingsTests.cs
Labels: breaking-change

#73 Add Bors
  .github/workflows/test.yml
  CONTRIBUTING.md
  bors.toml
Labels: skip-changelog
