Repository meilisearch/meilisearch-dotnet, pull requests merged in 2021-12, with the labels that each got.

#197 Remove dependancy on Microsoft.AspNetCore.WebUtilities
  src/Meilisearch/Index.cs
  src/Meilisearch/Meilisearch.csproj
  src/Meilisearch/ObjectExtensions.cs
  tests/Meilisearch.Tests/Meilisearch.Tests.csproj
  tests/Meilisearch.Tests/ObjectExtensionsTests.cs
Labels: enhancement, dependencies

#203 Update README and code samples
  .code-samples.meilisearch.yaml
  README.md
Labels: skip-changelog

#205 Update logo
  README.md
Labels: skip-changelog

#201 Batch Operations quickfix
  src/Meilisearch/Index.cs
  tests/Meilisearch.Tests/DocumentTests.cs
Labels: bug
