Repository meilisearch/meilisearch-dotnet, pull requests merged in 2022-02, with the labels that each got.

#232 Add Date objects in the Key instantiation in the code samples
  .code-samples.meilisearch.yaml
Labels: documentation, skip-changelog

#233 Feature/Analytics
  .github/workflows/tests.yml
  src/Meilisearch/Version.cs
  tests/Meilisearch.Tests/VersionTests.cs
Labels: enhancement

#230 Create a GetChunks extension method for batches
  src/Meilisearch/Extensions/EnumerableExtensions.cs
  src/Meilisearch/Index.cs
Labels: enhancement

#236 Make sure AddDocuments and UpdateDocuments have the same behaviour
  src/Meilisearch/Constants.cs
  src/Meilisearch/Extensions/HttpExtensions.cs
  src/Meilisearch/Index.cs
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/ObjectExtensions.cs
  tests/Meilisearch.Tests/DocumentTests.cs
Labels: enhancement

#241 Feature/Analytics
  src/Meilisearch/Extensions/HttpExtensions.cs
  src/Meilisearch/MeilisearchClient.cs
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
Labels: enhancement

#237 Remove leading slash from api paths
  .env
  .github/workflows/pre-release-tests.yml
  .github/workflows/tests.yml
  .gitignore
  docker-compose.yml
  nginx.conf
  src/Meilisearch/Extensions/StringExtensions.cs
  src/Meilisearch/Index.cs
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/TaskEndpoint.cs
  tests/Meilisearch.Tests/ClientFactory.cs
  tests/Meilisearch.Tests/DocumentTests.cs
  tests/Meilisearch.Tests/IndexFixture.cs
  tests/Meilisearch.Tests/IndexTests.cs
  tests/Meilisearch.Tests/KeyTests.cs
  tests/Meilisearch.Tests/Meilisearch.Tests.csproj
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
  tests/Meilisearch.Tests/ObjectExtensionsTests.cs
  tests/Meilisearch.Tests/SearchTests.cs
  tests/Meilisearch.Tests/ServerConfigs/BaseUriServer.cs
  tests/Meilisearch.Tests/ServerConfigs/ProxiedUriServer.cs
  tests/Meilisearch.Tests/SettingsTests.cs
  tests/Meilisearch.Tests/StringExtensionsTests.cs
  tests/Meilisearch.Tests/TaskInfoTests.cs
  tests/Meilisearch.Tests/VersionTests.cs
Labels: bug, enhancement

#246 Update version for the next release (v0.10.0)
  src/Meilisearch/Meilisearch.csproj
Labels: skip-changelog
