Repository meilisearch/meilisearch-dotnet, pull requests merged in 2022-12, with the labels that each got.

#365 Rename TaskInfoQuery fields (IndexUids & Statuses)
  src/Meilisearch/Index.Tasks.cs
  src/Meilisearch/QueryParameters/TasksQuery.cs
  tests/Meilisearch.Tests/TaskInfoTests.cs
Labels: breaking-change

#369 Enhancement/Object extensions
  src/Meilisearch/Extensions/ObjectExtensions.cs
  tests/Meilisearch.Tests/ObjectExtensionsTests.cs
Labels: enhancement

#367 Feature/Add cancel tasks
  src/Meilisearch/Key.cs
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/QueryParameters/CancelTasksQuery.cs
  src/Meilisearch/TaskEndpoint.cs
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
Labels: enhancement

#370 Feature/Add filters to tasks
  src/Meilisearch/Extensions/ObjectExtensions.cs
  src/Meilisearch/QueryParameters/TasksQuery.cs
Labels: enhancement

#372 Feature/Add delete tasks
  src/Meilisearch/Key.cs
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/QueryParameters/DeleteTasksQuery.cs
  src/Meilisearch/TaskEndpoint.cs
  src/Meilisearch/TaskInfo.cs
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
Labels: enhancement

#374 Update version for the next release (v0.12.2)
  src/Meilisearch/Meilisearch.csproj
Labels: skip-changelog

#378 Add documentation for intellisense when publishing package
  src/Meilisearch/Index.Documents.cs
  src/Meilisearch/Meilisearch.csproj
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/Settings.cs
Labels: skip-changelog
