Repository meilisearch/meilisearch-dotnet, pull requests merged in 2022-01, with the labels that each got.

#207 Rename all async methods with an Async suffix
  .code-samples.meilisearch.yaml
  README.md
  src/Meilisearch/Extensions/HttpExtensions.cs
  src/Meilisearch/Index.cs
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/MeilisearchMessageHandler.cs
  tests/Meilisearch.Tests/DocumentTests.cs
  tests/Meilisearch.Tests/IndexFixture.cs
  tests/Meilisearch.Tests/IndexTests.cs
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
  tests/Meilisearch.Tests/SearchTests.cs
  tests/Meilisearch.Tests/SettingsTests.cs
  tests/Meilisearch.Tests/UpdateStatusTests.cs
Labels: breaking-change

#209 Remove DeleteIfExists and DeleteIndexIfExists methods
  src/Meilisearch/Index.cs
  src/Meilisearch/MeilisearchClient.cs
  tests/Meilisearch.Tests/IndexTests.cs
Labels: breaking-change

#210 Remove useless tests regarding DeleteIndexIfExists
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
Labels: skip-changelog

#211 Use `Authorization` header instead of `X-Meili-API-Key`
  src/Meilisearch/Extensions/HttpExtensions.cs
  tests/Meilisearch.Tests/ClientFactory.cs
Labels: breaking-change

#212 Remove all warnings during compile time
  src/Meilisearch/Extensions/HttpExtensions.cs
  src/Meilisearch/Index.cs
  src/Meilisearch/MeilisearchClient.cs
  tests/Meilisearch.Tests/ObjectExtensionsTests.cs
Labels: skip-changelog

#215 Changes regarding new task API
  .code-samples.meilisearch.yaml
  README.md
  src/Meilisearch/DumpStatus.cs
  src/Meilisearch/Index.cs
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/Result.cs
  src/Meilisearch/TaskEndpoint.cs
  src/Meilisearch/TaskInfo.cs
  src/Meilisearch/UpdateStatus.cs
  tests/Meilisearch.Tests/DocumentTests.cs
  tests/Meilisearch.Tests/IndexFixture.cs
  tests/Meilisearch.Tests/IndexTests.cs
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
  tests/Meilisearch.Tests/SearchTests.cs
  tests/Meilisearch.Tests/SettingsTests.cs
  tests/Meilisearch.Tests/TaskInfoTests.cs
  tests/Meilisearch.Tests/UpdateStatusTests.cs
Labels: breaking-change

#217 Add methods regarding API keys
  src/Meilisearch/Key.cs
  src/Meilisearch/MeilisearchClient.cs
  src/Meilisearch/TaskInfo.cs
  tests/Meilisearch.Tests/KeyTests.cs
Labels: enhancement

#219 Code samples MeiliSearch v0.25.0
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#222 Change version for the next release (v0.9.0)
  src/Meilisearch/Meilisearch.csproj
Labels: skip-changelog

#226 Use DateTime when the property is related to a Date
  src/Meilisearch/Key.cs
  tests/Meilisearch.Tests/KeyTests.cs
Labels: enhancement, breaking-change

#223 Upgrade Meilisearch project to .NET Standard 2.1
  README.md
  src/Meilisearch/Meilisearch.csproj
Labels: enhancement, breaking-change, security

#228 Remove underscore from private field
  .github/workflows/tests.yml
  src/Meilisearch/Index.cs
  src/Meilisearch/MeilisearchClient.cs
Labels: enhancement

#229 Enrich nuget data of Meilisearch .net package
  src/Meilisearch/Meilisearch.csproj
Labels: skip-changelog
