Repository meilisearch/meilisearch-dotnet, pull requests merged in 2022-10, with the labels that each got.

#319 Update version for the next release (v0.12.0)
  src/Meilisearch/Meilisearch.csproj
Labels: skip-changelog, breaking-change

#335 Removes duplicate test assertion in IndexTests.cs
  tests/Meilisearch.Tests/IndexTests.cs
Labels: skip-changelog, maintenance, hacktoberfest

#337 Use dataset files instead of handwritten data for tests
  tests/Meilisearch.Tests/Datasets.cs
  tests/Meilisearch.Tests/Datasets/movies_for_faceting.json
  tests/Meilisearch.Tests/Datasets/movies_with_info.json
  tests/Meilisearch.Tests/Datasets/movies_with_int_id.json
  tests/Meilisearch.Tests/Datasets/movies_with_string_id.json
  tests/Meilisearch.Tests/DocumentTests.cs
  tests/Meilisearch.Tests/IndexFixture.cs
  tests/Meilisearch.Tests/Meilisearch.Tests.csproj
  tests/Meilisearch.Tests/Utils.cs
Labels: enhancement, maintenance, hacktoberfest

#338 Add pagination settings
  .code-samples.meilisearch.yaml
  src/Meilisearch/Index.Pagination.cs
  src/Meilisearch/Pagination.cs
  src/Meilisearch/Settings.cs
  tests/Meilisearch.Tests/SettingsTests.cs
Labels: enhancement, hacktoberfest

#354 Mark Enabled as a nullable boolean value.
  src/Meilisearch/TypoTolerance.cs
  tests/Meilisearch.Tests/SettingsTests.cs
Labels: hacktoberfest, hacktoberfest-accepted
