Repository meilisearch/meilisearch-dotnet, pull requests merged in 2023-03, with the labels that each got.

#402 Add TotalHits and TotalPages fields to PaginatedSearchResult
  src/Meilisearch/PaginatedSearchResult.cs
  tests/Meilisearch.Tests/SearchTests.cs
Labels: breaking-change

#403 Update version for the next release (v0.14.0)
  src/Meilisearch/Meilisearch.csproj
Labels: skip-changelog

#405 use JsonContent instead of StringContent
  src/Meilisearch/Extensions/HttpExtensions.cs
Labels: enhancement

#404 remove nulls when updating documents
  src/Meilisearch/Extensions/HttpExtensions.cs
  src/Meilisearch/Index.Documents.cs
  tests/Meilisearch.Tests/DocumentTests.cs
Labels: bug
