Repository meilisearch/meilisearch-dotnet, pull requests merged in 2025-01, with the labels that each got.

#603 Make RankingScoreThreshold optional
  src/Meilisearch/SearchQuery.cs
Labels: bug

#592 Add Facet search support
  .code-samples.meilisearch.yaml
  src/Meilisearch/FacetSearchQuery.cs
  src/Meilisearch/FacetSearchResult.cs
  src/Meilisearch/Index.Documents.cs
  tests/Meilisearch.Tests/FacetSearchTests.cs
  tests/Meilisearch.Tests/ServerConfigs/BaseUriServer.cs
  tests/Meilisearch.Tests/ServerConfigs/ProxiedUriServer.cs
Labels: enhancement

#579 Update search docs
  .code-samples.meilisearch.yaml
  README.md
Labels: maintenance

#594 Add searchCutoffMs setting support
  .code-samples.meilisearch.yaml
  src/Meilisearch/Index.SearchCutoffMs.cs
  src/Meilisearch/Meilisearch.csproj
  src/Meilisearch/Settings.cs
  tests/Meilisearch.Tests/SettingsTests.cs
Labels: enhancement

#593 Add snapshot creation method
  .code-samples.meilisearch.yaml
  src/Meilisearch/MeilisearchClient.cs
  tests/Meilisearch.Tests/MeilisearchClientTests.cs
Labels: enhancement

#606 Attempt to fix publish.yml
  .github/workflows/publish.yml
Labels: maintenance

#611 clean up syntax of Test project
  tests/Meilisearch.Tests/DocumentTests.cs
  tests/Meilisearch.Tests/IndexSwapTest.cs
  tests/Meilisearch.Tests/Movie.cs
  tests/Meilisearch.Tests/MultiIndexSearchTests.cs
  tests/Meilisearch.Tests/Properties/launchSettings.json
  tests/Meilisearch.Tests/SearchTests.cs
  tests/Meilisearch.Tests/ServerConfigs/BaseUriServer.cs
  tests/Meilisearch.Tests/ServerConfigs/ProxiedUriServer.cs
  tests/Meilisearch.Tests/SettingsTests.cs
  tests/Meilisearch.Tests/TaskInfoTests.cs
Labels: maintenance

#612 Add runtimeconfig
  src/Meilisearch/runtimeconfig.json
Labels: maintenance

#613 Drop support of Dotnet 6, use Dotnet 9 instead
  .github/workflows/tests.yml
  tests/Meilisearch.Tests/Meilisearch.Tests.csproj
Labels: breaking-change

#615 Update Meilisearch.csproj fix publish
  src/Meilisearch/Meilisearch.csproj
Labels: bug

#614 another attempt to fix publish.yml
  .github/workflows/publish.yml
Labels: bug

#616 Drop dotnet 6 , update to net8
  .github/workflows/tests.yml
  tests/Meilisearch.Tests/Meilisearch.Tests.csproj
Labels: breaking-change

#617 Update publish.yml
  .github/workflows/publish.yml
Labels: maintenance

#619 Update README.md
  README.md
Labels: documentation
